import Head from 'next/head';
import { Box, Divider } from '@chakra-ui/react';
import Footer from '../components/footer';
import NavBar from '../components/navbar';
import DonationForm from '../components/donationForm';
import DonationList from '../components/donationList';

export default function DonationPage({ data }) {

	if (!data) return <></>
	return (
		<div>
			<Head>
				<title>IDP | Donations</title>
				<meta name='description' content='Generated by IDP management System' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Box maxW='1000px' mx='auto' p={'3'}>
					<NavBar />
					<Divider orientation='vertical' height='50px' />
					<DonationForm />
					<Divider orientation='vertical' height='100px' />
					<DonationList data={data} />
					<Divider orientation='vertical' height='50px' />
				</Box>
				<Footer />
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const res = await fetch('http://localhost:3333/api/v1/donations');
	const data = await res.json();

	return { props: { data } };
}
