import Head from 'next/head';
import { Box, Divider } from '@chakra-ui/react';
import Footer from '../components/footer';
import NavBar from '../components/navbar';
import ExpensesForm from '../components/expensesForm';
import ExpensesList from '../components/expensesList';
import { useEffect, useState } from 'react';

export default function ExpensePage({ data }) {
	const [admin, setAdmin] = useState(false);
	useEffect(() => {
		const status = localStorage.getItem('ADMIN_ACCESS');
		setAdmin(() => (status === 'false' ? false : true));
	});
	if (!data) return <></>;
	return (
		<div>
			<Head>
				<title>IDP | Expenses</title>
				<meta name='description' content='Generated by IDP management System' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Box maxW='1000px' mx='auto' p={'3'}>
					<NavBar />
					<Divider orientation='vertical' height='50px' />
					{admin && <ExpensesForm />}
					<Divider orientation='vertical' height='100px' />
					<ExpensesList data={data} />
					<Divider orientation='vertical' height='50px' />
				</Box>
				<Footer />
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const res = await fetch('http://localhost:3333/api/v1/expenses');
	const data = await res.json();

	return { props: { data } };
}
