import Head from 'next/head';
import Image from 'next/image';
import { Box, Divider } from '@chakra-ui/react';
import Footer from '../components/footer';
import NavBar from '../components/navbar';
import NewsPost from '../components/news';
import Content from '../components/content';

export default function Home() {
	return (
		<div>
			<Head>
				<title>IDP Management System</title>
				<meta name='description' content='Generated by IDP management System' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Box maxW='1000px' mx='auto' p={'3'}>
					<NavBar />
					<Divider orientation='vertical' height='50px' />

					<Box borderRadius='10' overflow='hidden'>
						<Image
							src='/images/refugee.jpg'
							alt='Refugee Images'
							width={1024}
							height={512}
						/>
					</Box>
					<Divider orientation='vertical' height='50px' />
					<Content />
					<Divider orientation='vertical' height='70px' />
					<NewsPost />
				</Box>
				<Divider orientation='vertical' height='70px' />
				<Footer />
			</main>
		</div>
	);
}
