import Head from 'next/head';
import { Box, Button, Container, Divider, FormLabel, Input } from '@chakra-ui/react';
import Footer from '../components/footer';
import NavBar from '../components/navbar';
import Router from 'next/router';
import { useEffect, useState } from 'react';

export default function LoginPage() {
  const [admin, setAdmin] = useState(false);
	useEffect(() => {
		const status = localStorage.getItem('ADMIN_ACCESS');
		setAdmin(() => (status === 'false' ? false : true));
	});
	const handleSubmit = async (event) => {
		event.preventDefault();

		const data = {
			username: event.target.name.value,
			password: event.target.password.value,
		};

		if (data.username.toLowerCase() === 'aisha' && data.password === '123456') {
      alert(`Hi Admin, welcome back!`);
      localStorage.setItem('ADMIN_ACCESS', 'true');
      Router.push('/')
		} else {
      alert(`Invalid Login credentials`);
      localStorage.setItem('ADMIN_ACCESS', 'false');
      Router.reload()
		}
	};
	return (
		<div>
			<Head>
				<title>Admin Login</title>
				<meta name='description' content='Generated by IDP management System' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Box maxW='1000px' mx='auto' p={'3'}>
					<NavBar />
					<Divider orientation='vertical' height='50px' />
					<Container borderRadius={'10'} p={'16'} background={'gray.300'}>
						<form onSubmit={handleSubmit}>
							<FormLabel htmlFor='first'>Username</FormLabel>
							<Input type='text' id='name' name='name' required />

							<FormLabel htmlFor='password'>Password</FormLabel>
							<Input type='password' id='password' name='password' required />

							<Button mt={4} colorScheme='teal' type='submit'>
								{admin? 'Logout' : 'Login'}
							</Button>
						</form>
					</Container>
				</Box>
				<Divider orientation='vertical' height='250px' />
				<Footer />
			</main>
		</div>
	);
}
