import Head from 'next/head';
import { Box, Divider, Heading, List, ListIcon, ListItem, MdCheckCircle } from '@chakra-ui/react';
import Footer from '../components/footer';
import NavBar from '../components/navbar';
import RefugeeList from '../components/refugeeList';
import RefugeeForm from '../components/refugeeForm';
import { useEffect, useState } from 'react';

export default function RefugeePage({ data }) {

	const [admin, setAdmin] = useState(false);
	useEffect(() => {
		const status = localStorage.getItem('ADMIN_ACCESS');
		setAdmin(() => (status === 'false' ? false : true));
	});
	if (!data) return <></>;
	return (
		<div>
			<Head>
				<title>IDPs</title>
				<meta name='description' content='Generated by IDP management System' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Box maxW='1000px' mx='auto' p={'3'}>
					<NavBar />
					<Divider orientation='vertical' height='50px' />
					{admin && <RefugeeForm />}
					<Divider orientation='vertical' height='100px' />
					<RefugeeList data={data} />
					<Divider orientation='vertical' height='50px' />

					<Heading>Our Statistics</Heading>
					<Divider orientation='vertical' height='25px' />
					<List spacing={3}>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							72% of children are out of school
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							50% of the people are vulnerable
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							25% of the people are living with disability
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							45% are windows
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							10% mortality rate
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Year of return for returnees - 25%
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Means of livelihood - 30%
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Farming - 30%
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Trading - 16%
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Fishing - 12%
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Military - 17%
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Local Authority - 8%
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Community - 2%
						</ListItem>
						<ListItem>
							<ListIcon as={MdCheckCircle} color='green.500' />
							Self-organized - 52%
						</ListItem>
					</List>
					<Divider orientation='vertical' height='50px' />
				</Box>
				<Footer />
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const res = await fetch('http://localhost:3333/api/v1/persons');
	const data = await res.json();

	return { props: { data } };
}
