import Head from 'next/head';
import Image from 'next/image';
import { Box, Center, Divider, Stack } from '@chakra-ui/react';
import Footer from '../components/footer';
import NavBar from '../components/navbar';
import RefugeeList from '../components/refugeeList';
import RefugeeForm from '../components/refugeeForm';

export default function RefugeePage({ data }) {
	if (!data) return <></>;
	return (
		<div>
			<Head>
				<title>IDP | Refugees</title>
				<meta name='description' content='Generated by IDP management System' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Box maxW='1000px' mx='auto' p={'3'}>
					<NavBar />
					<Divider orientation='vertical' height='50px' />
					<RefugeeForm />
					<Divider orientation='vertical' height='100px' />
					<RefugeeList data={data} />
					<Divider orientation='vertical' height='50px' />
				</Box>
				<Footer />
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const res = await fetch('http://localhost:3333/api/v1/persons');
	const data = await res.json();

	return { props: { data } };
}
